name: Build and update pages

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and deploy to pages
    steps:
      - name: Install all dependencies
        run: npm i

      - name: Build
        run: npm run build